_core:
  default_config_hash: wbD9a1lSFlzefyZbT7berzkarufh5L0yc5p0e9pywE4
version: v3
disabled: false
rest_api_url: 'https://akab-xlvql4tugln6a7r7-rvonelw7asu2cvfd.luna.akamaiapis.net'
storage_method: key
client_token: akamai_client_token
client_secret: akamai_client_secret
access_token: akamai_access_token
edgerc_path: ''
edgerc_section: default
basepath: 'https://stage.mass.gov'
timeout: 10
domain:
  production: false
  staging: true
action_v3:
  delete: false
  invalidate: true
log_requests: true
edge_cache_tag_header: false
purge_urls_with_hostname: false
edge_cache_tag_header_blacklist: {  }
edgescape_support: false
