timeout: 14400
max_timeout: 172800
padding: 20
role_logout: false
redirect_url: /user/login
no_dialog: false
message: 'Your session is about to expire. Do you want to reset it?'
inactivity_message: 'You have been logged out due to inactivity.'
enforce_admin: true
jstimer_format: '%hours%:%mins%:%secs%'
jstimer_js_load_option: false
use_alt_logout_method: false
use_watchdog: true
_core:
  default_config_hash: zJS1GknUylh656CJSNXOupqKSqm6Xw200h1cq1eI970
