status: 1
pattern: '[node:field_regulation_agency_cmr] CMR [node:field_regulation_cmr_chapter]: [node:field_regulation_title]'
dependencies:
  config:
    - node.type.regulation
new_content_behavior: 1
php: false
