license_key: eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NjgzNDg3OTksImp0aSI6IjZlMjczNmY0LTE0NzEtNGU3OS05N2VhLTliODg5Mzc4NjVhOSIsInVzYWdlRW5kcG9pbnQiOiJodHRwczovL3Byb3h5LWV2ZW50LmNrZWRpdG9yLmNvbSIsImRpc3RyaWJ1dGlvbkNoYW5uZWwiOlsiY2xvdWQiLCJkcnVwYWwiLCJzaCJdLCJ3aGl0ZUxhYmVsIjp0cnVlLCJsaWNlbnNlVHlwZSI6InRyaWFsIiwiZmVhdHVyZXMiOlsiKiJdLCJ2YyI6ImNlNGM3YTkwIn0.AQfVsv1CTHP2WctQ0l1f0mxIMfkh6T0h-sp-Ob1IeAc9H37jhCrz8pgcwks9Du24vfJK_c4u9YVNGmf6RPOilg
auth_type: dev_token
env: ''
access_key: suhsjNOJY8VEyPgB8qXMaXNBj8F8Jx8x5Qx6h0JojjZdIGAcf0Kfl47TjUJIqHm8CQ2IGKWe1HXRBhhJskVtxcb9asW5y-oGVU3a_HflhzRfPrFxXpaLw4i7
web_socket_url: 'wss://zt8296skvcs7.cke-cs.com/ws'
dev_token_url: 'https://zt8296skvcs7.cke-cs.com/token/dev/48422964ee6ad881b4ff5be625a741b07927e0c94f0a9eef0d58aa4290b1?limit=10'
dev_token_accept: 1
dll_location: 'https://cdn.ckeditor.com/ckeditor5/VERSION_TOKEN/dll/'
organization_id: zt8296skvcs7
alter_node_form_css: false
add_key_to_all_instances: 0
api_key: MzVqCWpdirR9QLTAA_wB6HobkXN4kriJGP2nGxXq-xzycUFDNKfcO9qrSocXIsgaB2eXQEQR9etfu9IWSydClVorxys7vCsdX0lRDGDGV68Y4CRJnpHc2flH
api_url: 'https://zt8296skvcs7.cke-cs.com/api/v5/sTfIxdIOD6NuRjsA_luJ'
