_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
mode: simple
ignored_config_entities:
  - 'ai_seo.report_type.*'
  - emoji_validation.settings
  - mass_alerts.settings
  - mass_utility.settings
  - user.mail
