definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  mass_dashboard__my_work:
    weight: -48
    menu_name: mass-dashboard
    parent: ''
    enabled: true
    expanded: false
  mass_dashboard__needs_review:
    weight: -47
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_dashboard__all_content:
    weight: -46
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_dashboard__redirect:
    weight: -43
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: false
  mass_dashboard__service_content:
    weight: -42
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: false
  mass_dashboard__all_documents:
    weight: -41
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_dashboard__orphaned_service_details:
    weight: -40
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: false
  mass_feedback_loop__mass_feedback_loop_author_interface_form:
    weight: -43
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_dashboard__trash:
    weight: -38
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_admin_toolbar__add_content:
    weight: -50
    menu_name: mass-dashboard
    parent: ''
    enabled: true
    expanded: false
  mass_admin_toolbar__add_document:
    weight: -49
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_admin_toolbar__my_work:
    weight: -39
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: false
  mass_admin_toolbar__needs_review:
    weight: -47
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_admin_toolbar__all_content:
    weight: -46
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_admin_toolbar__all_documents:
    weight: -45
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  mass_admin_toolbar__trash:
    weight: -41
    menu_name: mass-dashboard
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: 0
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
