track_enabled_base_fields: true
local_task_enabled_entity_types:
  - media
  - node
  - taxonomy_term
usage_controller_items_per_page: 25
_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
track_enabled_source_entity_types:
  - node
  - paragraph
track_enabled_target_entity_types:
  - media
  - node
  - paragraph
  - taxonomy_term
edit_warning_message_entity_types: {  }
delete_warning_message_entity_types: {  }
track_enabled_plugins:
  - dynamic_entity_reference
  - entity_reference
  - html_link
  - link
  - linkit
site_domains:
  - www.mass.gov
