_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - media
  - node
  - taxonomy_term
  - paragraphs_library_item
track_enabled_source_entity_types:
  - node
  - paragraph
track_enabled_target_entity_types:
  - node
  - media
  - paragraph
  - taxonomy_term
track_enabled_plugins:
  - dynamic_entity_reference
  - entity_reference
  - html_link
  - link
  - linkit
  - media_entity_download_html_link
track_enabled_base_fields: true
site_domains:
  - www.mass.gov
  - mass.gov
edit_warning_message_entity_types:
  - paragraphs_library_item
delete_warning_message_entity_types:
  - paragraphs_library_item
usage_controller_items_per_page: 25
usage_controller_subquery: true
