cache: true
_core:
  default_config_hash: 51p0N1fcuoTUrOlPIReSbz6lCjo-zJRgB5VSq7FGk3Y
plugins_options:
  arcgisonline:
    sourcecountry: ''
    usessl: false
  bingmaps:
    apikey: ''
    locale: ''
  geonames:
    username: ''
    locale: ''
  googlemaps:
    apikey: ''
    locale: ''
    region: ''
    usessl: true
  ipinfodb:
    apikey: ''
    precision: city
  mapquest:
    apikey: ''
    licensed: false
  maxmind:
    apikey: ''
    service: f
    usessl: false
  nominatim:
    rooturl: ''
    locale: ''
  opencage:
    apikey: 'REDACTED. See settings.php.'
    locale: ''
    usessl: true
  tomtom:
    apikey: ''
    locale: ''
  file: {  }
  freegeoip: {  }
  geoip: {  }
  geoplugin: {  }
  gpxfile: {  }
  hostip: {  }
  openstreetmap: {  }
  random: {  }
  yandex: {  }
