_core:
  default_config_hash: xJXu4TTseY6TsTB3CtrOJr4efB1rKHENvLaORKRiPTo
iframe_resizer_usage:
  host: true
  hosted: false
iframe_resizer_advanced:
  target_type: specific
  target_selectors: iframe.js-iframe-resizer
  override_defaults: false
  options:
    log: false
    heightCalculationMethod: bodyOffset
    widthCalculationMethod: scroll
    autoResize: true
    bodyBackground: ''
    bodyMargin: ''
    inPageLinks: true
    interval: 32
    maxHeight: -1
    maxWidth: -1
    minHeight: 0
    minWidth: 0
    resizeFrom: parent
    scrolling: false
    sizeHeight: true
    sizeWidth: false
    tolerance: 0
iframe_resizer_advanced_hosted_options:
  targetOrigin: '*'
  heightCalculationMethod: parent
  widthCalculationMethod: parent
