features:
  node_user_picture: 0
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
  path: themes/custom/mass_theme/images/stateseal.png
  mimetype: image/png
languages:
  ar: ar
  es: es
  fr: fr
  ht: ht
  it: it
  km: km
  ko: ko
  pl: pl
  pt: pt
  ru: ru
  vi: vi
  zh-CN: zh-CN
  aa: 0
  ab: 0
  af: 0
  am: 0
  as: 0
  ay: 0
  az: 0
  ba: 0
  be: 0
  bg: 0
  bh: 0
  bi: 0
  bn: 0
  bo: 0
  br: 0
  ca: 0
  co: 0
  cs: 0
  cy: 0
  da: 0
  de: 0
  dz: 0
  el: 0
  eo: 0
  et: 0
  eu: 0
  fa: 0
  fi: 0
  fj: 0
  fo: 0
  fy: 0
  ga: 0
  gd: 0
  gl: 0
  gn: 0
  gu: 0
  ha: 0
  hi: 0
  hr: 0
  hu: 0
  hy: 0
  ia: 0
  ie: 0
  ik: 0
  in: 0
  is: 0
  iw: 0
  ja: 0
  ji: 0
  jw: 0
  ka: 0
  kk: 0
  kl: 0
  kn: 0
  ks: 0
  ku: 0
  ky: 0
  la: 0
  ln: 0
  lo: 0
  lt: 0
  lv: 0
  mg: 0
  mi: 0
  mk: 0
  ml: 0
  mn: 0
  mo: 0
  mr: 0
  ms: 0
  mt: 0
  my: 0
  na: 0
  ne: 0
  nl: 0
  'no': 0
  oc: 0
  om: 0
  pa: 0
  ps: 0
  qu: 0
  rm: 0
  rn: 0
  ro: 0
  rw: 0
  sa: 0
  sd: 0
  sg: 0
  sh: 0
  si: 0
  sk: 0
  sl: 0
  sm: 0
  sn: 0
  so: 0
  sq: 0
  sr: 0
  ss: 0
  st: 0
  su: 0
  sv: 0
  sw: 0
  ta: 0
  te: 0
  tg: 0
  th: 0
  ti: 0
  tk: 0
  tl: 0
  tn: 0
  to: 0
  tr: 0
  ts: 0
  tt: 0
  tw: 0
  uk: 0
  ur: 0
  uz: 0
  vo: 0
  wo: 0
  xh: 0
  yo: 0
  zu: 0
