entity_type_groups:
  file:
    file:
      basic: basic
  flagging:
    watch_content:
      basic: basic
  media:
    document:
      basic: basic
    media_video:
      basic: basic
  node:
    action:
      basic: basic
      advanced: advanced
    advisory:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
    alert:
      basic: basic
      advanced: advanced
    binder:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
      mass_metatag: mass_metatag
    campaign_landing:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
    contact_information:
      basic: basic
      advanced: advanced
    curated_list:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
      mass_metatag: mass_metatag
    decision:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
    decision_tree:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    decision_tree_branch:
      basic: basic
      advanced: advanced
    decision_tree_conclusion:
      basic: basic
      advanced: advanced
    error_page:
      basic: basic
      advanced: advanced
    event:
      basic: basic
      advanced: advanced
    executive_order:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
    fee:
      basic: basic
      advanced: advanced
    form_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
    guide_page:
      basic: basic
      advanced: advanced
    how_to_page:
      basic: basic
      advanced: advanced
    info_details:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
      schema_special_announcement: schema_special_announcement
      mass_metatag: mass_metatag
    interstitial:
      basic: basic
      advanced: advanced
    location:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
    location_details:
      basic: basic
      advanced: advanced
    news:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
      schema_special_announcement: schema_special_announcement
    org_page:
      basic: basic
      advanced: advanced
    page:
      basic: basic
      advanced: advanced
    person:
      basic: basic
      advanced: advanced
    regulation:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
    rules:
      basic: basic
      advanced: advanced
      schema_special_announcement: schema_special_announcement
    service_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      twitter_cards: twitter_cards
      schema_government_service: schema_government_service
      schema_special_announcement: schema_special_announcement
      schema_unit_price_specification: schema_unit_price_specification
      mass_metatag: mass_metatag
    stacked_layout:
      basic: basic
      advanced: advanced
    topic_page:
      basic: basic
      advanced: advanced
    utility_drawer:
      basic: basic
  redirect:
    redirect:
      basic: basic
  taxonomy_term:
    action_type:
      basic: basic
    adjustment_type:
      basic: basic
    advisory_publish_state:
      basic: basic
    advisory_type:
      basic: basic
    announcement_type:
      basic: basic
    binder_type:
      basic: basic
    content_type:
      basic: basic
    decision_participant_type:
      basic: basic
    decision_type:
      basic: basic
    document_category:
      basic: basic
    document_contacts:
      basic: basic
    document_creators:
      basic: basic
    document_other_type:
      basic: basic
    document_subjects:
      basic: basic
    document_tags:
      basic: basic
    event_type:
      basic: basic
    icons:
      basic: basic
    label:
      basic: basic
    language:
      basic: basic
    license:
      basic: basic
    location_activities:
      basic: basic
    location_icon:
      basic: basic
    location_icon_park:
      basic: basic
    rules_of_court_standing_order:
      basic: basic
    rules_of_court_type:
      basic: basic
    tags:
      basic: basic
    type:
      basic: basic
    user_organization:
      basic: basic
  user:
    user:
      basic: basic
