_core:
  default_config_hash: NFnOZU6VCOfURCAR4-O3V7eMHTx2LNqnCmDKRSNjjns
always_save_userinfo: false
connect_existing_users: true
override_registration_settings: false
end_session_enabled: false
user_login_display: replace
redirect_login: ''
redirect_logout: ''
userinfo_mappings:
  timezone: zoneinfo
  user_picture: picture
role_mappings:
  author: {  }
  editor: {  }
  emergency_alert_publisher: {  }
  executive_orders: {  }
  redirect_creators: {  }
  content_team: {  }
  developer: {  }
  administrator: {  }
  tester: {  }
  doc_deletion: {  }
  d2d_redirect_manager: {  }
  data_administrator: {  }
  collection_administrator: {  }
