id: default_massit
label: 'Default MassIT'
password_reset: 0
langcode: en
policy_constraints:
  -
    id: password_length
    character_length: 8
    character_operation: minimum
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: uppercase
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: numeric
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: special
  -
    id: password_policy_character_constraint
    character_count: 1
    character_type: lowercase
roles:
  authenticated: authenticated
  content_team: content_team
  developer: developer
  administrator: administrator
