_core:
  default_config_hash: azSZG6PzCOEObVe6w8oHNHYnnpmshoZLUIedRu-EsjY
processing_enabled: 1
client_id: 'Random string'
client_secret: 'Random string'
batch_size: '5'
retry_limit: '3'
page_size_threshold: 500000
email_notifications:
  enabled: 0
  include_report: 0
notification_fallback_uid: null
