_core:
  default_config_hash: azSZG6PzCOEObVe6w8oHNHYnnpmshoZLUIedRu-EsjY
processing_enabled: true
client_id: ''
client_secret: ''
batch_size: 5
retry_limit: 3
page_size_threshold: 500000
email_notifications:
  enabled: true
  include_report: true
notification_fallback_uid: null
