_core:
  default_config_hash: FtwnuCXmazPAh2H2i_gbDhMK1-eBmNy1dG4RBU4qt4o
langcode: en
display_denied_message: false
access_denied_message: 'Access denied. You must log in to view this page.'
access_denied_message_type: error
redirect_authenticated_users_to: ''
throw_authenticated_404: false
display_auth_denied_message: true
access_denied_auth_message: 'Access denied. Check with your site administrator if you need assistance.'
access_denied_auth_message_type: error
user_login_path: /user/login
default_redirect_code: 307
add_noindex_header: false
destination_parameter_override: ''
match_noredirect_pages: "/user/reset/*\r\n/user/password*\r\n*---unpublished*"
match_noredirect_negate: 0
redirect_to_destination: true
