route_iframes:
  route_iframe_base_url: ''
  route_iframe_main_tab_name: ''
  route_iframe_main_tab_path: ''
  route_iframe_tabs: {  }
_core:
  default_config_hash: SCSeejYI40t9apPVH89iwf6DQRr6nOIOs-tA7i14fEo
route_iframe_base_url: 'https://dashboards.digital.mass.gov'
route_iframe_main_tab_name: Analytics
route_iframe_main_tab_path: analytics
route_iframe_tabs:
  1:
    name: Default
    path: dashboards
