enabled: 1
send_plugins: {  }
login_plugins: {  }
validation_plugin: tfa_totp
validation_plugin_settings:
  tfa_totp:
    time_skew: 30
    site_name_prefix: 0
    name_prefix: MASS
    issuer: MASS.GOV
  tfa_hotp:
    counter_window: 10
    site_name_prefix: 1
    name_prefix: TFA
    issuer: Drupal
fallback_plugins:
  tfa_totp:
    tfa_recovery_code:
      enable: 1
      settings:
        recovery_codes_amount: 9
      weight: -2
  tfa_hotp:
    tfa_recovery_code:
      enable: 1
      settings:
        recovery_codes_amount: 9
      weight: -2
help_text: "<p>ERROR:<br />\r\nUse the link that was emailed to you to login. Please submit a <a href=\"https://massgov.service-now.com/sp?id=sc_cat_item&amp;sys_id=0bb8e784dbec0700f132fb37bf9619fe\">ServiceNow request</a> for assistance.</p>\r\n"
validation_skip: 0
encryption: real_aes
trust_cookie_expiration: 2592000
cookie_name: TFA
tfa_flood_uid_only: 1
tfa_flood_window: 300
tfa_flood_threshold: 6
_core:
  default_config_hash: MhrA-cxuU_zfd1goV-WFbz-4AFXhlvniyVyDdNBcims
required_roles:
  author: author
  editor: editor
  emergency_alert_publisher: emergency_alert_publisher
  executive_orders: executive_orders
  redirect_creators: redirect_creators
  content_team: content_team
  developer: developer
  administrator: administrator
  tester: tester
  authenticated: '0'
  doc_deletion: '0'
  campaign_landing_page_publisher: '0'
  d2d_redirect_manager: '0'
allowed_validation_plugins:
  tfa_totp: tfa_totp
default_validation_plugin: tfa_totp
mail:
  tfa_enabled_configuration:
    subject: 'edit.mass.gov two-factor authentication enabled'
    body: "Dear [user:display-name],\r\n\r\nThank you for setting up two-factor authentication (also known as multifactor authentication) on your account at edit.mass.gov. Please remember that you will need your authentication method (your cell phone or desktop software) ready every time you log in. \r\n\r\nIf you lose your device, you can use one of your recovery codes to log in. Then you can disable your existing two-factor setup and re-enable two-factor with a new device. If you have not taken note of your recovery codes, please do so the next time you log in. Store them in a safe place! \r\n\r\n-- Massachusetts Digital Service "
  tfa_disabled_configuration:
    subject: 'edit.mass.gov two-factor authentication disabled'
    body: "Dear [user:display-name], \r\n\r\nYour two-factor authentication on edit.mass.gov has been disabled. \r\n\r\nYou will need to re-enable two-factor authentication the next time you log in. \r\n\r\n--Massachusetts Digital Service "
