mass_alerts.settings:
  type: config_object
  label: 'Mass Alerts settings'
  mapping:
    excluded_org_ids:
      type: sequence
      label: 'Hidden organization node IDs'
      sequence:
        type: integer
